#!/usr/bin/env bash

couchDbInitIndicator=/var/lib/couchdb/couchdb-not-inited

if [[ -e $couchDbInitIndicator ]]; then
  echo "Initialising CouchDB..."
  initialise_couchdb
  rm -f $couchDbInitIndicator
fi

echo "Starting CouchDB..."
/usr/local/bin/couchdb

exit 0
